name: Auto Minify JS and CSS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: HTML/CSS/JS Minifier
        uses: devatherock/minify-js@v2.0.0
        with:
          directory: .
          output: mini
          add_suffix: false

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Minified files" && git push)
