name: Auto Minify JS and CSS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Auto Minify
        uses: marketplace-actions/html-css-js-minifier@master
        with:
          args: --input . --output ./mini --overwrite
        
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Minified files" && git push)
