name: Auto Minify JS and CSS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Auto Minify
        uses: nizarmah/auto-minify@v2.1.1
        with:
          destination: mini
          overwrite: true
