name: Auto Minify JS and CSS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Auto Minify
        uses: nizarmah/auto-minify@v2.1
        with:
          directory: .
          output: mini
          overwrite: true

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Minified files" && git push)
