name: Minify JavaScript

on:
  push:
    branches:
      - main  # Replace with your default branch name if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: refs/heads/main  # Replace with your default branch name if it's not 'main'
          token: ${{ secrets.GH_TOKEN }}

      - name: Minify JavaScript files
        uses: nizarmah/auto-minify@v1
        with:
          type: "js"
          source: "."
          destination: "mini"

      - name: Commit and push
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add mini/*
          git commit -m "Minified JS" || echo "No changes to commit"
          git push origin main  # Replace with your default branch name if it's not 'main'
